apiVersion: v1
kind: Service
metadata:
  name: redis #specified in the python code of vote app
  labels:
    app: redis
spec:
  type: ClusterIP #default
  ports: 
    - name: redis-service
      port: 6379
      targetPort: 6379
  selector:
    app: redis #forward traffic to all pods matching this label