apiVersion: v1
kind: Service
metadata:
  name: result 
  labels:
    app: result
spec:
  type: NodePort
  ports: 
    - name: result-service
      port: 8080 #request coming to this serviceip:8080 will be forwarded to pod:80
      targetPort: 80
      nodePort: 31001
  selector:
    app: result