apiVersion: v1
kind: Service
metadata:
  name: vote 
  labels:
    app: vote
spec:
  type: NodePort
  ports: 
    - name: vote-service
      port: 8080 #request coming to this serviceip:8080 will be forwarded to pod:80
      targetPort: 80
      nodePort: 31000
  selector:
    app: vote